#!/usr/bin/bash
set ratios 1:2:3
set previewer ~/.config/lf/preview
set cleaner ~/.config/lf/cleaner

cmd edit_detached ${{
  if [ -d "$f" ]; then
    setsid -f alacritty --class nvim -e /bin/nvim \
      -c ":cd $f" -c ":Telescope find_files" >/dev/null 2>&1
  else
    setsid -f alacritty --class nvim -e /bin/nvim \
      -c ":cd $(dirname "$f")" -- "$f" >/dev/null 2>&1
  fi
}}

cmd open_detached_terminal ${{
  [[ -f "$f" ]] && f=$(dirname "$f")
  nohup alacritty --working-directory "$f" >/dev/null 2>&1 &
}} 

cmd list_images ${{
	nohup swiv -t -b "$f" > /dev/null &
}}

map e edit_detached "$f"
map a open_detached_terminal "$f"
map x list_images "$f"
