# Window
window-maximized=no
keepaspect=yes
autofit=100%x100%
panscan=0
autofit-larger=336x336  # 16 * 21
force-window=yes  # window wo video
audio-display=no  
script-opts-append=osc-visibility=auto  # alaways show controls
background-color=0/0

# Video
hwdec=nvdec
vo=gpu
gpu-api=vulkan
#vf-add=fps=30:round=near  # from 60 to 30

# Audio
ao=pulse
volume=70

# yt-dlp
script-opts=ytdl_hook-ytdl_path=yt-dlp
ytdl-format="(bv*[height=1920][vcodec~='^(vp9|avc1|h264)']+ba)/(bv*[height=1280][vcodec~='^(vp9|avc1|h264)']+ba)/(bv*[height=1080][vcodec~='^(vp9|avc1|h264)']+ba)/(bv*[height=720][vcodec~='^(vp9|avc1|h264)']+ba)/(bv*[height=1920]+ba)/(bv*[height=1280]+ba)/(bv*[height=1080]+ba)/(bv*[height=720]+ba)/(bv*+ba/b)"
ytdl-raw-options=live-from-start=

# Sub
sub-color='#FFFF00'
sub-font='Cascaydia Cove Nerd Font'
sub-font-size=60
sub-ass-override=yes

# Screenshot
screenshot-directory='~/pictures/screenshots/'
screenshot-template="%ts"
